### ISSUE TITLE
wx not works in python2.7-wxpython docker image

### ISSUE THREAD

**Issue by chiu0602** [luzh/dockerfiles#1]
It seems essential binary is removed after building of wxPython, error returned when importing wx library.

In the docker container:

```
# python
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wx

```

**Comment by luzh** [comment]
Please run 'python2.7' (or /usr/local/bin/python2.7) instead of 'python'. In this CentOS image 'python' is reserved for the system. You can check this script for a test run: https://github.com/luzh/dockerfiles/blob/master/python/2.7/wxpython/imagetest.py

You also need to set up the graphical environment properly for the docker image. There are relevant notes in https://github.com/luzh/dockerfiles/blob/master/README.md

**Comment by chiu0602** [comment]
Thanks for your help! I can import wx now.
